const sampleRelay=`周五 ——19点一21点
场地：洋湖一号场（包含门将限制二十四人）
报名（实名认证）接龙

1: 大王
2: 门将张亮
3: 门将小王
4: 阳
5: 周 宇
6: 老游
7: 王龙
8: 老鱼
9: 红犀牛
10: 库库雷利平
11: 俊锟·㉿
12: 番十三
13: 果之林
14: 康饼
15: zengQ
16: Michael
17: 尚涛
18: 石三Nathan
19: 啊比比
20: 柳旭
21: 小何
22: 欧巴
23: 小庄
24: snow
25: 摩托萨克
26: 蒲蒲
27: 雷洲 先报上`;
const teamMeta={red:{name:"红队"},green:{name:"绿队"},white:{name:"白队"}};
const $=s=>document.querySelector(s),$all=s=>[...document.querySelectorAll(s)];
const emptyTeams=()=>({red:{players:[],gk:null,positions:{}},green:{players:[],gk:null,positions:{}},white:{players:[],gk:null,positions:{}}});
const emptyBoard=()=>({label:"",annotations:[]});
const state={players:[],teams:emptyTeams(),captains:{red:null,green:null,white:null},draftOrder:["red","green","white"],gkOrder:["red","green","white"],draftQueue:[],currentPickIndex:-1,timerId:null,secondsLeft:60,currentLineupTeam:"red",tactics:{red:emptyBoard(),green:emptyBoard(),white:emptyBoard()},activeTool:"attack",drawing:null};
function escapeHtml(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function parseRelay(text){return text.split(/\r?\n/).map(x=>x.trim().match(/^(\d+)\s*[:：.、]\s*(.+)$/)).filter(Boolean).map(m=>{let content=m[2].trim();const isGk=/^(门将|GK|守门员)\s*/i.test(content);content=content.replace(/^(门将|GK|守门员)\s*/i,"").trim();const noteMatch=content.match(/\s+(先报上|晚到|待定|临时|蹭球|\+1|带人.*)$/);const name=noteMatch?content.slice(0,noteMatch.index).trim():content;return{id:`p-${m[1]}-${name}`,order:Number(m[1]),name,note:noteMatch?noteMatch[1].trim():"",isGk,isReserve:Number(m[1])>24}})}
function card(p,opt={}){const badges=`${p.isGk?'<span class="badge gk">GK</span> ':''}${p.isReserve?'<span class="badge">候补</span> ':''}${p.note?`<span class="badge">${escapeHtml(p.note)}</span>`:''}`;return`<div class="player-card"><span class="number">${p.order??""}</span><div><strong>${escapeHtml(p.name)}</strong> ${badges}</div>${opt.action?`<button data-action="${opt.action}" data-id="${p.id}">${opt.label}</button>`:""}</div>`}
function empty(t){return`<div class="player-card"><span></span><div>${t}</div><span></span></div>`}
function renderLists(){const confirmed=state.players.filter(p=>!p.isReserve),reserves=state.players.filter(p=>p.isReserve);$("#confirmedList").innerHTML=confirmed.map(card).join("")||empty("暂无正式报名");$("#reserveList").innerHTML=reserves.map(card).join("")||empty("暂无候补");$("#activityStatus").textContent=confirmed.length?`${confirmed.length}人已导入`:"未导入";renderSetup()}
function syncCaptainSelections(){["red","green","white"].forEach(t=>{const s=$("#captain-"+t);if(s?.value)state.captains[t]=s.value})}
function renderSetup(){syncCaptainSelections();const confirmed=state.players.filter(p=>!p.isReserve),opts=confirmed.map(p=>`<option value="${p.id}">${escapeHtml(p.name)}</option>`).join("");["red","green","white"].forEach(t=>{const s=$("#captain-"+t);s.innerHTML=`<option value="">请选择</option>${opts}`;if(state.captains[t])s.value=state.captains[t]});$("#gkPoolList").innerHTML=confirmed.filter(p=>p.isGk).map(card).join("")||empty("还没有 GK");$("#editableList").innerHTML=confirmed.map(p=>`<div class="player-card"><span class="number">${p.order}</span><div><strong>${escapeHtml(p.name)}</strong> ${p.isGk?'<span class="badge gk">GK</span>':''}</div><button data-action="toggle-gk" data-id="${p.id}">${p.isGk?"取消GK":"标记GK"}</button></div>`).join("")}
function setStep(step){$all(".step").forEach(b=>b.classList.toggle("is-active",b.dataset.step===step));$all(".panel").forEach(p=>p.classList.remove("is-active"));$("#panel-"+step).classList.add("is-active")}
function parseOrder(v){const valid=new Set(["red","green","white"]),arr=v.split(",").map(x=>x.trim()).filter(x=>valid.has(x));return arr.length?arr:["red","green","white"]}
function findPlayer(id){return state.players.find(p=>p.id===id)}
function applySetup(){syncCaptainSelections();const ids=Object.values(state.captains).filter(Boolean);if(new Set(ids).size!==ids.length)return alert("三个队长不能选择同一个人。");if(ids.length<3)return alert("请先指定红、绿、白三个队长。");state.draftOrder=parseOrder($("#draftOrderInput").value);state.gkOrder=parseOrder($("#gkOrderInput").value);resetDraft();setStep("draft")}
function resetDraft(){stopTimer();state.teams=emptyTeams();["red","green","white"].forEach(t=>{const c=findPlayer(state.captains[t]);if(c)state.teams[t].players.push(c.id)});state.draftQueue=buildDraftQueue();state.currentPickIndex=-1;state.secondsLeft=60;renderDraft();renderLineup()}
function buildDraftQueue(){const q=[],captains=new Set(Object.values(state.captains).filter(Boolean));const normal=state.players.filter(p=>!p.isReserve&&!p.isGk&&!captains.has(p.id));for(let i=0;i<Math.min(normal.length,18);i++)q.push({team:state.draftOrder[i%state.draftOrder.length],type:"player"});for(let i=0;i<3;i++)q.push({team:state.gkOrder[i%state.gkOrder.length],type:"gk"});return q}
function assignedIds(){const s=new Set;Object.values(state.teams).forEach(t=>{t.players.forEach(id=>s.add(id));if(t.gk)s.add(t.gk)});return s}
function available(type){const used=assignedIds();return state.players.filter(p=>!p.isReserve&&!used.has(p.id)&&(type==="gk"?p.isGk:!p.isGk))}
function renderDraft(){const cur=state.draftQueue[state.currentPickIndex];$("#currentPick").textContent=cur?`${teamMeta[cur.team].name}选择${cur.type==="gk"?"GK（最后选）":"球员"}`:state.currentPickIndex>=state.draftQueue.length-1?"选人完成":"等待开始";$("#timer").textContent=String(state.secondsLeft);$("#availablePlayers").innerHTML=(available(cur?.type||"player").map(p=>card(p,{action:"pick-player",label:cur?"选择":"待选"})).join("")||empty("暂无可选球员"));$("#draftTeams").innerHTML=["red","green","white"].map(t=>{const roster=state.teams[t].players.map(findPlayer).filter(Boolean),gk=findPlayer(state.teams[t].gk);return`<article class="team-card ${t}"><h3>${teamMeta[t].name} · ${roster.length}${gk?"+GK":""}</h3><div class="team-roster">${[...roster.map(card),gk?card({...gk,isGk:true}):""].join("")||empty("等待选人")}</div></article>`}).join("")}
function startDraft(){if(state.currentPickIndex===-1)state.currentPickIndex=0;renderDraft();startTimer()}
function startTimer(){stopTimer();state.secondsLeft=60;$("#timer").textContent="60";state.timerId=setInterval(()=>{state.secondsLeft--;$("#timer").textContent=String(state.secondsLeft);if(state.secondsLeft<=0)autoPick()},1000)}function stopTimer(){if(state.timerId)clearInterval(state.timerId);state.timerId=null}
function pickPlayer(id){const cur=state.draftQueue[state.currentPickIndex];if(!cur)return;if(cur.type==="gk")state.teams[cur.team].gk=id;else state.teams[cur.team].players.push(id);state.currentPickIndex++;if(state.currentPickIndex>=state.draftQueue.length){stopTimer();state.secondsLeft=0;renderDraft();applyFormation("3-3-1");setStep("lineup");return}renderDraft();startTimer()}
function autoPick(){const cur=state.draftQueue[state.currentPickIndex];if(!cur)return;const list=available(cur.type);if(!list.length){state.currentPickIndex++;if(state.currentPickIndex>=state.draftQueue.length){stopTimer();renderDraft();applyFormation("3-3-1");setStep("lineup");return}renderDraft();startTimer();return}pickPlayer(list[Math.floor(Math.random()*list.length)].id)}
const formationSlots={"3-3-1":[[50,88],[24,68],[50,68],[76,68],[24,43],[50,43],[76,43],[50,18]],"2-3-2":[[50,88],[36,68],[64,68],[24,45],[50,45],[76,45],[38,20],[62,20]],"3-2-2":[[50,88],[24,68],[50,68],[76,68],[38,44],[62,44],[38,20],[62,20]]};
function applyFormation(name){const slots=formationSlots[name],team=state.teams[state.currentLineupTeam];if(!slots||!team)return;team.positions={};[team.gk,...team.players].filter(Boolean).slice(0,8).forEach((id,i)=>team.positions[id]={x:slots[i][0],y:slots[i][1]});renderLineup()}
function renderLineup(){const team=state.teams[state.currentLineupTeam],pitch=$("#pitch"),ids=[team.gk,...team.players].filter(Boolean),board=state.tactics[state.currentLineupTeam]||emptyBoard();pitch.innerHTML=renderAnnotations(board.annotations);ids.forEach((id,i)=>{if(!team.positions[id]){const f=formationSlots["3-3-1"][i]||[50,50];team.positions[id]={x:f[0],y:f[1]}}const p=findPlayer(id);if(!p)return;const pos=team.positions[id],el=document.createElement("div"),isGk=id===team.gk;el.className=`player-token ${state.currentLineupTeam}${isGk?" is-gk":""}`;el.dataset.id=id;el.style.left=pos.x+"%";el.style.top=pos.y+"%";el.style.transform="translate(-50%,-50%)";el.textContent=isGk?`GK · ${p.name}`:p.name;pitch.appendChild(el)});$("#bench").innerHTML=state.players.filter(p=>p.isReserve).map(p=>`<span class="bench-chip">${escapeHtml(p.name)}</span>`).join("")||'<span class="bench-chip">暂无候补</span>';$("#tacticsTitle").textContent=teamMeta[state.currentLineupTeam].name+"战术板";$("#annotationText").value=board.label;$all(".team-tab").forEach(tab=>tab.classList.toggle("is-active",tab.dataset.team===state.currentLineupTeam));enableDragging();enableBoardDrawing()}
function renderAnnotations(a){return a.map(x=>{if(x.type==="area"){const l=Math.min(x.x,x.x2),t=Math.min(x.y,x.y2),w=Math.abs(x.x2-x.x),h=Math.abs(x.y2-x.y);return`<div class="board-area board-mark" data-id="${x.id}" style="left:${l}%;top:${t}%;width:${w}%;height:${h}%">${escapeHtml(x.text)}</div>`}if(x.type==="note")return`<div class="board-note board-mark" data-id="${x.id}" style="left:${x.x}%;top:${x.y}%">${escapeHtml(x.text)}</div>`;const dx=x.x2-x.x,dy=x.y2-x.y,w=Math.max(4,Math.hypot(dx,dy)),ang=Math.atan2(dy,dx)*180/Math.PI;return`<div class="board-arrow ${x.type} board-mark" data-id="${x.id}" style="left:${x.x}%;top:${x.y}%;width:${w}%;transform:rotate(${ang}deg)"><span>${escapeHtml(x.text)}</span></div>`}).join("")}
function saveBoard(){state.tactics[state.currentLineupTeam]={...state.tactics[state.currentLineupTeam],label:$("#annotationText").value.trim()}}
function point(e){const r=$("#pitch").getBoundingClientRect();return{x:Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100)),y:Math.max(0,Math.min(100,(e.clientY-r.top)/r.height*100))}}
function text(f){return $("#annotationText").value.trim()||f}
function enableBoardDrawing(){const pitch=$("#pitch");pitch.onpointerdown=e=>{if(e.target.closest(".player-token"))return;const mark=e.target.closest(".board-mark");if(state.activeTool==="erase"){if(mark)removeAnnotation(mark.dataset.id);return}if(mark)return;const p=point(e);if(state.activeTool==="note"){addAnnotation({type:"note",x:p.x,y:p.y,text:text("提醒")});return}if(!["attack","defense","area"].includes(state.activeTool))return;state.drawing={type:state.activeTool,x:p.x,y:p.y,x2:p.x,y2:p.y,text:text(state.activeTool==="area"?"控制区域":"跑位")};pitch.setPointerCapture(e.pointerId)};pitch.onpointermove=e=>{if(!state.drawing)return;const p=point(e);state.drawing.x2=p.x;state.drawing.y2=p.y};pitch.onpointerup=()=>{if(!state.drawing)return;const d=state.drawing;state.drawing=null;if(Math.hypot(d.x2-d.x,d.y2-d.y)<3)return;addAnnotation(d)}}
function addAnnotation(a){saveBoard();state.tactics[state.currentLineupTeam].annotations.push({id:`a-${Date.now()}-${Math.random().toString(16).slice(2)}`,...a});renderLineup()}function removeAnnotation(id){const b=state.tactics[state.currentLineupTeam];b.annotations=b.annotations.filter(a=>a.id!==id);renderLineup()}function clearCurrentBoard(){saveBoard();state.tactics[state.currentLineupTeam].annotations=[];renderLineup()}function undoLastAnnotation(){saveBoard();state.tactics[state.currentLineupTeam].annotations.pop();renderLineup()}
async function exportCurrentBoard(){saveBoard();const payload=JSON.stringify(state.tactics[state.currentLineupTeam],null,2);try{await navigator.clipboard.writeText(payload);alert("当前队战术已复制为 JSON。")}catch{prompt("复制当前队战术 JSON：",payload)}}function importCurrentBoard(){const raw=prompt("粘贴战术 JSON：");if(!raw)return;try{const parsed=JSON.parse(raw);if(!Array.isArray(parsed.annotations))throw Error();state.tactics[state.currentLineupTeam]={label:parsed.label||"",annotations:parsed.annotations};renderLineup()}catch{alert("导入失败，请确认 JSON 来自本战术板。")}}
function enableDragging(){$all(".player-token").forEach(el=>{el.addEventListener("pointerdown",e=>{const pitch=$("#pitch"),r=pitch.getBoundingClientRect();el.setPointerCapture(e.pointerId);const move=ev=>{const x=Math.max(8,Math.min(92,(ev.clientX-r.left)/r.width*100)),y=Math.max(8,Math.min(92,(ev.clientY-r.top)/r.height*100));el.style.left=x+"%";el.style.top=y+"%";state.teams[state.currentLineupTeam].positions[el.dataset.id]={x,y}};const up=()=>{el.removeEventListener("pointermove",move);el.removeEventListener("pointerup",up)};el.addEventListener("pointermove",move);el.addEventListener("pointerup",up)})})}
function resetPositions(){state.teams[state.currentLineupTeam].positions={};renderLineup()}
function bindEvents(){$all(".step").forEach(b=>b.onclick=()=>setStep(b.dataset.step));$("#loadSampleBtn").onclick=()=>$("#relayInput").value=sampleRelay;$("#clearBtn").onclick=()=>$("#relayInput").value="";$("#parseBtn").onclick=()=>{state.players=parseRelay($("#relayInput").value);renderLists();setStep("setup")};$("#editableList").onclick=e=>{const b=e.target.closest('button[data-action="toggle-gk"]');if(!b)return;const p=findPlayer(b.dataset.id);if(p)p.isGk=!p.isGk;renderSetup()};$("#applySetupBtn").onclick=applySetup;["red","green","white"].forEach(t=>$("#captain-"+t).addEventListener("change",syncCaptainSelections));$("#startDraftBtn").onclick=startDraft;$("#autoPickBtn").onclick=autoPick;$("#resetDraftBtn").onclick=resetDraft;$("#availablePlayers").onclick=e=>{const b=e.target.closest('button[data-action="pick-player"]');if(b)pickPlayer(b.dataset.id)};$all("[data-formation]").forEach(b=>b.onclick=()=>applyFormation(b.dataset.formation));$("#resetPositionsBtn").onclick=resetPositions;$all(".team-tab").forEach(tab=>tab.onclick=()=>{saveBoard();state.currentLineupTeam=tab.dataset.team;renderLineup()});$("#saveTacticsBtn").onclick=()=>{saveBoard();renderLineup();$("#saveTacticsBtn").textContent="已保存";setTimeout(()=>$("#saveTacticsBtn").textContent="保存战术板",900)};$("#annotationText").onblur=saveBoard;$("#clearBoardBtn").onclick=clearCurrentBoard;$("#undoBoardBtn").onclick=undoLastAnnotation;$("#exportBoardBtn").onclick=exportCurrentBoard;$("#importBoardBtn").onclick=importCurrentBoard;$all(".tool-btn").forEach(b=>b.onclick=()=>{state.activeTool=b.dataset.tool;$all(".tool-btn").forEach(x=>x.classList.toggle("is-active",x===b))})}
bindEvents();renderLists();renderDraft();renderLineup();